spring:
  profiles:
    active: dev
  application:
    name: task-management-service

server:
  port: 8080

# Common configurations
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.talentica.taskmanagement: INFO
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

jwt:
  secret: mySecretKeyWhichIslongEnough256TobeProtected
  expiration: 86400000 # 24 hours in milliseconds